#! /bin/bash 

nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__8_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_8.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__9_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_9.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__22_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_22.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__23_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_23.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__24_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_24.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__25_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_25.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__26_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_26.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__27_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_27.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__28_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_28.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__29_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_29.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__30_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_30.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__31_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_31.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__32_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_32.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__33_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_33.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__34_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_34.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__35_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_35.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__36_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_36.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__37_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_37.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__38_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_38.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__39_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_39.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__40_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_40.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__41_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_41.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__42_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_42.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__43_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_43.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__44_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_44.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__45_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_45.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__46_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_46.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__47_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_47.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__48_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_48.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__49_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_49.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__50_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_50.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__51_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_51.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__52_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_52.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__53_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_53.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__54_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_54.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__55_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_55.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__56_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_56.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__57_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_57.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__58_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_58.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__59_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_59.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__60_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_60.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__61_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_61.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__62_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_62.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__63_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_63.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__64_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_64.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__65_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_65.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__66_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_66.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__67_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_67.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__68_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_68.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__69_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_69.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__70_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_70.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__71_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_71.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__72_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_72.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__73_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_73.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__74_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_74.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__75_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_75.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__76_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_76.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__77_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_77.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__78_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_78.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__79_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_79.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__80_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_80.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__81_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_81.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__82_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_82.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__83_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_83.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__84_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_84.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__85_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_85.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__86_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_86.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__87_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_87.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__88_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_88.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__89_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_89.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__90_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_90.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__91_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_91.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__92_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_92.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__93_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_93.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__94_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_94.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__95_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_95.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__96_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_96.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__97_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_97.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__98_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_98.txt  & 
nohup /usr/bin/Rscript  /home/ubuntu/*/*/get_comb_of_len12from24parameters__99_job.R > /mnt/AUC_1//Len_12/Results_combs_len12_99.txt  & 
